PACKAGE=cbase64-erlang-nif
REPO=git://github.com/urbanserj/${PACKAGE}.git

include ../../common.mk

prepare:
	ln -s cbase64.app.src ${PACKAGE}/src/cbase64.app
	ln -s ../ebt.config ${PACKAGE}/ebt.config
