PACKAGE=ibrowse
REPO=git://github.com/cmullaparthi/${PACKAGE}.git

include ../../common.mk

prepare:
	ln -s ${PACKAGE}.app.src ${PACKAGE}/src/${PACKAGE}.app
	ln -s ../ebt.config ${PACKAGE}/ebt.config

