PACKAGE=meck
REPO=git://github.com/eproxus/${PACKAGE}.git

include ../../common.mk

prepare:
	ln -s ${PACKAGE}.app.src ${PACKAGE}/src/${PACKAGE}.app
	ln -s ../ebt.config ${PACKAGE}/ebt.config
	rm -rf ${PACKAGE}/test


