PACKAGE=protobuffs
REPO=git://github.com/basho/erlang_protobuffs.git

include ../../common.mk

prepare:
	ln -s ${PACKAGE}.app.src ${PACKAGE}/src/${PACKAGE}.app
	ln -s ../ebt.config ${PACKAGE}/ebt.config

